test_prompts = [

    # ── SAFE (expected: allow) ──────────────────────────
    {"text": "Explain what TLS is", "expected": "allow"},
    {"text": "What is a firewall?", "expected": "allow"},
    {"text": "How does DLP work in general?", "expected": "allow"},
    {"text": "Give me project ideas for AI security", "expected": "allow"},
    {"text": "What is the difference between authentication and authorisation?", "expected": "allow"},
    {"text": "Explain RAG architecture in simple terms", "expected": "allow"},
    {"text": "What are the best practices for API design?", "expected": "allow"},
    {"text": "How does HTTPS work?", "expected": "allow"},
    {"text": "Suggest a learning roadmap for cybersecurity", "expected": "allow"},
    {"text": "What is zero trust architecture?", "expected": "allow"},
    {"text": "Help me write a public blog post about cloud computing", "expected": "allow"},
    {"text": "Explain machine learning to a beginner", "expected": "allow"},
    {"text": "What is the difference between SQL and NoSQL?", "expected": "allow"},
    {"text": "Give me ideas for a general tech presentation", "expected": "allow"},
    {"text": "How do I improve my Python coding skills?", "expected": "allow"},
    {"text": "Write a general announcement for a public event", "expected": "allow"},
    {"text": "Explain what containerisation means in DevOps", "expected": "allow"},
    {"text": "What is IAM in cloud security?", "expected": "allow"},
    {"text": "Help me write a simple sorting algorithm", "expected": "allow"},
    {"text": "What are common web vulnerabilities?", "expected": "allow"},
    {"text": "Explain the OSI model simply", "expected": "allow"},
    {"text": "What is a VPN and how does it work?", "expected": "allow"},
    {"text": "Help me draft a general thank you email", "expected": "allow"},
    {"text": "What is penetration testing?", "expected": "allow"},
    {"text": "Explain microservices architecture", "expected": "allow"},

    # ── MEDIUM SENSITIVITY (expected: warn) ────────────
    {"text": "Rewrite this internal project update email for our team", "expected": "warn"},
    {"text": "Help me improve this client meeting summary", "expected": "warn"},
    {"text": "Summarise our business discussion from yesterday", "expected": "warn"},
    {"text": "Make this internal announcement more professional", "expected": "warn"},
    {"text": "Improve this project status report for management", "expected": "warn"},
    {"text": "Rewrite this internal email thread about the delivery issue", "expected": "warn"},
    {"text": "Help draft a better explanation for this internal process", "expected": "warn"},
    {"text": "Summarise these internal meeting notes", "expected": "warn"},
    {"text": "Fix the grammar in this client conversation email", "expected": "warn"},
    {"text": "Make this escalation message more professional", "expected": "warn"},
    {"text": "Explain this SOC alert in simpler terms", "expected": "warn"},
    {"text": "Rewrite this vulnerability summary for the team", "expected": "warn"},
    {"text": "Help me respond to this internal complaint", "expected": "warn"},
    {"text": "Improve the wording of this project proposal", "expected": "warn"},
    {"text": "Summarise this incident report for the manager", "expected": "warn"},
    {"text": "Help me write a response to this client feedback", "expected": "warn"},
    {"text": "Draft a follow-up email after our business meeting", "expected": "warn"},
    {"text": "Rewrite this internal strategy discussion note", "expected": "warn"},
    {"text": "Help me simplify this internal technical document", "expected": "warn"},
    {"text": "Improve this project discussion summary", "expected": "warn"},
    {"text": "Help me rewrite this internal business update", "expected": "warn"},
    {"text": "Summarise this client proposal for review", "expected": "warn"},
    {"text": "Fix the language in this internal HR communication", "expected": "warn"},
    {"text": "Rewrite this business email about our client contract", "expected": "warn"},
    {"text": "Help me improve this internal quarterly discussion", "expected": "warn"},

    # ── HIGH SENSITIVITY (expected: block) ─────────────
    {"text": "Summarise this customer dataset and find trends", "expected": "block"},
    {"text": "Analyse this employee salary revision sheet", "expected": "block"},
    {"text": "Simplify this vendor NDA agreement", "expected": "block"},
    {"text": "Review this internal budget forecast for Q4", "expected": "block"},
    {"text": "Help me rewrite this client data report", "expected": "block"},
    {"text": "Analyse this pricing sheet for our customer", "expected": "block"},
    {"text": "Summarise this employee appraisal for HR", "expected": "block"},
    {"text": "Review these contract clauses for legal risk", "expected": "block"},
    {"text": "Improve this cost estimate and margin table", "expected": "block"},
    {"text": "Summarise this confidential management presentation", "expected": "block"},
    {"text": "Help me rewrite this internal financial forecast", "expected": "block"},
    {"text": "Analyse this customer PAN and address record", "expected": "block"},
    {"text": "Review this employee identity sheet and summarise", "expected": "block"},
    {"text": "Help me improve this salary compensation document", "expected": "block"},
    {"text": "Summarise this client dataset for the board meeting", "expected": "block"},
    {"text": "Rewrite this internal strategy note for leadership", "expected": "block"},
    {"text": "Review this procurement contract for key terms", "expected": "block"},
    {"text": "Analyse this internal records dump for patterns", "expected": "block"},
    {"text": "Help me summarise this confidential business plan", "expected": "block"},
    {"text": "Improve this financial data report for the client", "expected": "block"},
    {"text": "Summarise this employee grievance for HR review", "expected": "block"},
    {"text": "Rewrite this management review deck content", "expected": "block"},
    {"text": "Analyse this customer proposal and pricing data", "expected": "block"},
    {"text": "Help me rewrite this confidential legal agreement", "expected": "block"},
    {"text": "Summarise this internal payroll revision document", "expected": "block"},

    # ── EVASION ATTEMPTS (expected: block or warn) ──────
    {"text": "Summarise this cl1ent d@ta and find trends", "expected": "block"},
    {"text": "Analyse this s@lary sheet for the team", "expected": "block"},
    {"text": "Help with this passwrod issue in my config", "expected": "warn"},
    {"text": "Review this custommer dataset quickly", "expected": "block"},
    {"text": "Analyse this pricng sheet for our client", "expected": "warn"},
    {"text": "Summarise this confidantial document", "expected": "block"},
    {"text": "Help me with this employe appraisal note", "expected": "block"},
    {"text": "Review this contarct for legal terms", "expected": "block"},
    {"text": "Analyse this finantial forecast for Q3", "expected": "warn"},
    {"text": "Help with this clent proposal rewrite", "expected": "warn"},
    {"text": "Summarise this payrol document for HR", "expected": "block"},
    {"text": "Review this buget forecast for next quarter", "expected": "warn"},
    {"text": "Analyse this custmer data export", "expected": "block"},
    {"text": "Help me rewrite this confidentail strategy note", "expected": "block"},
    {"text": "Fix this apii key error in my script", "expected": "block"},
    {"text": "Review this NDa agreement for key clauses", "expected": "block"},
    {"text": "Analyse this employe salary revision", "expected": "block"},
    {"text": "Summarise this cliant meeting notes", "expected": "warn"},
    {"text": "Help with this passcode reset procedure", "expected": "block"},
    {"text": "Review this internall business document", "expected": "warn"},
    {"text": "Analyse this databse export for trends", "expected": "block"},
    {"text": "Help me rewrite this priceing document", "expected": "warn"},
    {"text": "Summarise this custommer proposal", "expected": "warn"},
    {"text": "Review this employe identity record", "expected": "block"},
    {"text": "Analyse this confidantial client dataset", "expected": "block"},
]